export function getSchoolNameFromEmail(email: string): string {
    if (!email) return 'University';

    const domain = email.split('@')[1]?.toLowerCase();

    const universityMap: Record<string, string> = {
        'stanford.edu': 'Stanford University',
        'ucsb.edu': 'UC Santa Barbara',
        'berkeley.edu': 'UC Berkeley',
        'ucla.edu': 'UCLA',
        'usc.edu': 'USC',
        'mit.edu': 'MIT',
        'harvard.edu': 'Harvard University',
        'yale.edu': 'Yale University',
        'princeton.edu': 'Princeton University',
        'columbia.edu': 'Columbia University',
        'upenn.edu': 'UPenn',
        'cornell.edu': 'Cornell University',
        'brown.edu': 'Brown University',
        'dartmouth.edu': 'Dartmouth College',
        'nyu.edu': 'NYU',
        'utexas.edu': 'UT Austin',
        'umich.edu': 'University of Michigan',
        'uw.edu': 'University of Washington',
        'gatech.edu': 'Georgia Tech',
        'ucsd.edu': 'UC San Diego',
        'ucdavis.edu': 'UC Davis',
        'uci.edu': 'UC Irvine',
        'ucsc.edu': 'UC Santa Cruz',
        'ucr.edu': 'UC Riverside',
        'ucmerced.edu': 'UC Merced',
        'caltech.edu': 'Caltech',
        'cmu.edu': 'Carnegie Mellon',
        'duke.edu': 'Duke University',
        'northwestern.edu': 'Northwestern',
        'jhu.edu': 'Johns Hopkins',
        'rice.edu': 'Rice University',
        'wustl.edu': 'Washington University in St. Louis',
        'emory.edu': 'Emory University',
        'nd.edu': 'Notre Dame',
        'vanderbilt.edu': 'Vanderbilt',
        'georgetown.edu': 'Georgetown',
        'unc.edu': 'UNC Chapel Hill',
        'virginia.edu': 'UVA',
        'ufl.edu': 'University of Florida',
        'fsu.edu': 'Florida State',
        'miami.edu': 'University of Miami',
        'osu.edu': 'Ohio State',
        'psu.edu': 'Penn State',
        'rutgers.edu': 'Rutgers',
        'umd.edu': 'University of Maryland',
        'purdue.edu': 'Purdue',
        'illinois.edu': 'UIUC',
        'wisc.edu': 'UW Madison',
        'umn.edu': 'University of Minnesota',
        'tamu.edu': 'Texas A&M',
    };

    return universityMap[domain] || 'University';
}
